### ISSUE TITLE
Remove `ValidatorInterface`

### ISSUE THREAD

**Issue by vjik** [yiisoft/validator#233]
Seems, `ValidatiorInterface` always will have one implementation only. Therefore, suggest remove him.

**Comment by samdark** [comment]
Fine to do it.

**Comment by samdark** [comment]
Yes, it does. Why should validator be extended?

**Comment by hyncica** [comment]
For example if you need to log validation for debugging purposes with `ValidatorInterface` you can easily decorate `Validator`:
```php
use Psr\Log\LoggerInterface;
use Yiisoft\Validator\Result;
use Yiisoft\Validator\ValidatorInterface;

final class ValidatorWithLog implements ValidatorInterface
{
    public function __construct(
        private readonly ValidatorInterface $validator,
        private readonly LoggerInterface $logger,
    ) {
    }
   
    public function validate(mixed $data, iterable $rules = []): Result
    {
        $result = $this->validator->validate($data, $rules);
        $this->logValidation($data, $rules, $result);
        return $result;
    }
    
    private function logValidation(mixed $data, iterable $rules, Result $result)
    {
        //... logging logic
    }
}
```
I can understand use of `final` because of open–closed principle. But if you make final class with public methods that are not part of some interface you are breaking "open for extension" part of that principle.

Also, there are other packages like `yiisoft/yii-middleware` or `yiisoft/request-model` that are dependent on that interface. If the interface is removed you will have to make them dependent on `Validator` directly. That will tighten coupling between those packages and validator package.

**Comment by vjik** [comment]
@hyncica, agree. this is valid case. We should keep interface.
