### ISSUE TITLE
Remove `LimitInterface` / `LimitTrait` / `LimitHandlerTrait`

### ISSUE THREAD

**Issue by samdark** [yiisoft/validator#381]
@vjik will write down details here later.

**Comment by vjik** [comment]
`LimitInterface`, like `LimitTrait`, used in rules `Count` and `HasLength` only.

Meaning of  `limit` is different in this rules: 
`Count` — min/max count elements;
`HasLength` — min/max length of string.

Very low probability (I think it's even a bad idea) to use `LimitInterface` and `LimitTrait` in userland.

Suggest remove `LimitInterface` and `LimitTrait`. Instead of, move code directly to rules and rule handlers. This is very simplify code.

**Comment by arogachev** [comment]
Discussed it within a team in a group chat and decided to keep them.
