### ISSUE TITLE
Add function exists to DataSetInterface

### ISSUE THREAD

**Issue by demonking** [yiisoft/validator#44]
```php

<?php
namespace Yiisoft\Validator;
/**
 * DataSetInterface represents a key-value data set
 */
interface DataSetInterface
{
    public function getValue(string $attribute);
    public function exists(string $attribute) :bool;
}

```
Would be nice to have a function exists() or isset() .

We try to access an attribute, which is not set, we receive an exception.

Lets see for example #12 the AtLeastValidator , which checks if the given attributes are set/filled.
When we try to implement it with `getValue()` we will have loop with a try&catch block... 
which I have to admit is a bad habit

**Comment by samdark** [comment]
That's OK to add it. Naming is important though:

1. It should be consistent. `getValue()` + `exists()` isn't.
2. It should not be too generic since these methods are likely to be implemented in a variety of different classes.

How about:

- `getAttributeValue(string $attribute)`
- `hasAttribute(string $attribute): bool`

**Comment by demonking** [comment]
how long will we take this under discussion? :)
Would like to implement it and the atleast, but don't know, if the decision will be rejected.

**Comment by samdark** [comment]
Won't be rejected. I'm on it.

**Comment by samdark** [comment]
Done.
